import json
import sys
from pathlib import Path
from datetime import datetime
from typing import Dict, List

sys.path.insert(0, str(Path(__file__).parent.parent))
from utils.openai_client import OpenAIClient

def generate_bugs_report(healing_analysis_path: str = "reports/healing_analysis.json") -> str:
    """
    Generate a detailed BUGS.md report from healing analysis.
    
    Args:
        healing_analysis_path: Path to healing analysis JSON file
    
    Returns:
        Path to generated BUGS.md file
    """
    project_root = Path(__file__).parent.parent.parent
    analysis_path = project_root / healing_analysis_path
    
    if not analysis_path.exists():
        print(f"Healing analysis file not found: {analysis_path}")
        return ""
    
    with open(analysis_path, "r") as f:
        analysis = json.load(f)
    
    actual_defects = analysis.get("actual_defects", [])
    
    if not actual_defects:
        print("No actual defects found - skipping BUGS.md generation")
        return ""
    
    print(f"Generating detailed bug report for {len(actual_defects)} defect(s)...")
    
    client = OpenAIClient()
    
    # Generate header
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    bugs_md = f"""# Bug Report

**Generated**: {timestamp}  
**Total Defects Found**: {len(actual_defects)}

---

## Summary

The AI test automation framework identified **{len(actual_defects)} potential bug(s)** in the application during test execution. These failures were classified as ACTUAL_DEFECT (not test errors) and require manual investigation.

---

## Defects Requiring Investigation

"""
    
    # Generate detailed analysis for each defect
    for idx, defect in enumerate(actual_defects, 1):
        test_name = defect.get("test_name", "Unknown")
        confidence = defect.get("confidence", "unknown")
        error = defect.get("error", "N/A")
        analysis = defect.get("analysis", "N/A")
        healing_attempts = defect.get("healing_attempts", 0)
        
        print(f"  Analyzing defect {idx}/{len(actual_defects)}: {test_name}")
        
        bugs_md += f"""### Bug #{idx}: {test_name}

**Confidence Level**: {confidence.upper()}  
**Classification**: ACTUAL_DEFECT  
"""
        
        if healing_attempts > 0:
            bugs_md += f"**Healing Attempts Before Classification**: {healing_attempts}  \n"
        
        bugs_md += f"""
**Error Message**:
```
{error}
```

**Initial AI Analysis**:
{analysis}

---

"""
        
        # Get detailed bug analysis from AI
        try:
            detailed_analysis = client.analyze_bug(defect)
            bugs_md += f"{detailed_analysis}\n\n---\n\n"
        except Exception as e:
            print(f"    Warning: Could not generate detailed analysis: {e}")
            bugs_md += f"*Detailed analysis unavailable*\n\n---\n\n"
    
    # Add footer
    bugs_md += f"""## Next Steps

1. **Review Each Bug**: Examine the detailed analysis above
2. **Prioritize**: Focus on high-confidence, critical severity bugs first
3. **Investigate**: Follow the suggested investigation areas
4. **Reproduce**: Use the reproduction steps to confirm the bug
5. **Fix**: Implement fixes based on potential solutions
6. **Verify**: Re-run tests after fixes to confirm resolution

## Notes

- These bugs were identified by AI analysis of test failures
- Confidence levels indicate AI's certainty about the classification
- Some bugs may be false positives - verify before fixing
- Tests that caught these bugs are NOT healed automatically
- Original test code preserved for bug reproduction

---

*Report generated by AI Test Automation Framework*
"""
    
    # Save BUGS.md
    bugs_path = project_root / "reports" / "BUGS.md"
    bugs_path.parent.mkdir(parents=True, exist_ok=True)
    
    with open(bugs_path, "w") as f:
        f.write(bugs_md)
    
    print(f"✓ Bug report saved to: {bugs_path}")
    
    return str(bugs_path)

if __name__ == "__main__":
    bugs_file = generate_bugs_report()
    if bugs_file:
        print(f"\nBug report generated: {bugs_file}")
    else:
        print("\nNo bugs to report")

